open Parser

(* Float numerals might lose precision *)
let string_of_tk = function
  | IF -> "If"
  | ELSE -> "Else"
  | RETURN -> "Return"
  | WHILE -> "While"
  | INT -> "Int"
  | CHAR -> "Char"
  | FLOAT -> "Float"
  | BOOL -> "Bool"
  | STRINGLITERAL str -> "StringLiteral(" ^ str ^ ")"
  | FLOATNUMERAL f -> "FloatNumeral(" ^ (string_of_float f) ^ ")"
  | INTNUMERAL i -> "IntNumeral(" ^ (string_of_int i) ^ ")"
  | TRUE -> "True"
  | FALSE -> "False"
  | PUT -> "@"
  | COLON -> ":"
  | SEMICOLON -> ";"
  | COMMA -> ","
  | ASSIGN -> "="
  | OPENBRACKET -> "["
  | CLOSEBRACKET -> "]"
  | OPENPAREN -> "("
  | CLOSEPAREN -> ")"
  | OPENBRACES -> "{"
  | CLOSEBRACES -> "}"
  | NEW -> "New"
  | AS -> "As"
  | ID str -> "Id(" ^ str ^ ")"
  | ADD -> "+"
  | SUB -> "-"
  | MUL -> "*"
  | DIV -> "/"
  | EQ -> "=="
  | NE -> "~="
  | LE -> "<="
  | GE -> ">="
  | LT -> "<"
  | GT -> ">"
  | AND -> "&&"
  | OR -> "||"
  | NOT -> "!"
  | EOF -> "EOF"


let print_tk = function
  | IF -> Printf.printf "If"
  | ELSE -> Printf.printf "Else"
  | RETURN -> Printf.printf "Return"
  | WHILE -> Printf.printf "While"
  | INT -> Printf.printf "Int"
  | CHAR -> Printf.printf "Char"
  | FLOAT -> Printf.printf "Float"
  | BOOL -> Printf.printf "Bool"
  | STRINGLITERAL str -> Printf.printf "StringLiteral(%s)" str
  | FLOATNUMERAL f -> Printf.printf "FloatNumeral(%h)" f
  | INTNUMERAL i -> Printf.printf "IntNumeral(%d)" i
  | TRUE -> Printf.printf "True"
  | FALSE -> Printf.printf "False"
  | PUT -> Printf.printf "@"
  | COLON -> Printf.printf ":"
  | SEMICOLON -> Printf.printf ";"
  | COMMA -> Printf.printf ","
  | ASSIGN -> Printf.printf "="
  | OPENBRACKET -> Printf.printf "["
  | CLOSEBRACKET -> Printf.printf "]"
  | OPENPAREN -> Printf.printf "("
  | CLOSEPAREN -> Printf.printf ")"
  | OPENBRACES -> Printf.printf "{"
  | CLOSEBRACES -> Printf.printf "}"
  | NEW -> Printf.printf "New"
  | AS -> Printf.printf "As"
  | ID str -> Printf.printf "Id(%s)" str
  | ADD -> Printf.printf "+"
  | SUB -> Printf.printf "-"
  | MUL -> Printf.printf "*"
  | DIV -> Printf.printf "/"
  | EQ -> Printf.printf "=="
  | NE -> Printf.printf "~="
  | LE -> Printf.printf "<="
  | GE -> Printf.printf ">="
  | LT -> Printf.printf "<"
  | GT -> Printf.printf ">"
  | AND -> Printf.printf "&&"
  | OR -> Printf.printf "||"
  | NOT -> Printf.printf "!"
  | EOF -> Printf.printf "EOF"

